### ISSUE TITLE
Errore dim. insiemi misurabili Lebesgue

### ISSUE THREAD

**Issue by cubanpit** [phaerrax/analisi-matematica#10]
Alla riga 469 del file sulla misura di Lebesgue (teorema 16.4.5) viene dimostrata la misurabilità di un insieme facendo riferimento al teorema 16.4.4, ma tal teorema nel suo enunciato non ha una "direzione" per cui si possa dimostrare la misurabilità dell'insieme protagonista.
Il teorema appare nella forma "Se E misurabile, allora . . ." e non "E misurabile se e solo se . . .".
Anche nella dimostrazione tale direzione non sembra dimostrata.
(Ho capito male io?)

**Comment by phaerrax** [comment]
Hai ragione, quell'enunciato è un po' confuso, non capisco nemmeno io cosa intendessi dire. A me ora verrebbe da interpretarlo come "se è misurabile allora..." il che non sarebbe buono per il teorema dopo :confused:

**Comment by cubanpit** [comment]
L'enunciato del teorema presente negli appunti va solo in una direzione, ma la direzione inversa è in realtà ovvia, probabilmente per questo motivo durante la lezione è stata saltata dal professore.
Tutto questo mi è stato chiarito dagli appunti sull'argomento a cui ha contribuito la Mamma.

**Comment by phaerrax** [comment]
Sarebbe meglio in ogni caso riformulare il teorema in modo più chiaro, almeno per far vedere che l'implicazione inversa _esiste_.
Oltretutto, anche se ovvia, è comunque bene aggiungere il pezzettino di dimostrazione.
